# Generated by Django 6.0.5 on 2026-05-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_so', models.CharField(max_length=50, unique=True)),
                ('pelanggan', models.CharField(max_length=200)),
                ('tanggal_so', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SELESAI', 'Selesai/Dikirim')], default='DRAFT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.barang')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='penjualan.salesorder')),
            ],
        ),
    ]
