# Generated by Django 6.0.5 on 2026-05-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResepProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_resep', models.CharField(help_text='Contoh: Resep Kain Greige Katun 30s', max_length=200)),
                ('jumlah_hasil', models.DecimalField(decimal_places=2, help_text='Jumlah target (misal: 1000)', max_digits=10)),
                ('produk_hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep_hasil', to='master_data.barang')),
            ],
        ),
        migrations.CreateModel(
            name='KomponenResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_dibutuhkan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resep_bahan', to='master_data.barang')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.resepproduksi')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_wo', models.CharField(help_text='Contoh: WO-2026-001', max_length=50, unique=True)),
                ('target_produksi', models.DecimalField(decimal_places=2, help_text='Jumlah yang ingin diproduksi', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROSES', 'Sedang Diproses'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], default='DRAFT', max_length=20)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produksi.resepproduksi')),
            ],
        ),
    ]
