# Generated by Django 6.0.5 on 2026-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
