# Generated by Django 6.0.5 on 2026-05-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gudang', models.CharField(default='Gudang Utama', max_length=100)),
                ('barang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master_data.barang')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipe', models.CharField(choices=[('MASUK', 'Barang Masuk'), ('KELUAR', 'Barang Keluar (Produksi)')], max_length=10)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.CharField(blank=True, max_length=200)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.barang')),
            ],
        ),
    ]
