# Generated by Django 6.0.5 on 2026-05-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_satuan', models.CharField(max_length=50)),
                ('simbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(help_text='Contoh: KTN-C30S-BLK', max_length=50, unique=True)),
                ('nama_barang', models.CharField(help_text='Contoh: Kain Katun Combed 30s Hitam', max_length=200)),
                ('tipe', models.CharField(choices=[('BAHAN_BAKU', 'Bahan Baku (Serat/Kimia)'), ('WIP', 'Setengah Jadi (Benang/Greige)'), ('PRODUK_JADI', 'Kain Jadi (Roll)')], max_length=20)),
                ('warna', models.CharField(blank=True, max_length=100, null=True)),
                ('ukuran_atau_gsm', models.CharField(blank=True, help_text='Ketebalan kain/benang', max_length=100, null=True)),
                ('harga_modal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.kategori')),
                ('satuan_utama', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_data.satuan')),
            ],
        ),
    ]
